on:
  push:
    branches:
      - main

name: Linux

jobs:
  release:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Edit Cargo.toml
        run: cp scripts/Cargo.toml .

      - name: Release Build
        run: cargo build --release

# todo: some testing
# releases?
