on:
  push:
    branches:
      - main

name: Mac Os

jobs:
  release:
    name: Mac Os
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Edit Cargo.toml
        run: cp scripts/Cargo.toml .

      - name: Release Build
        run: cargo build --release

      - name: Test
        run: |
          ./target/release/amethyst scripts/fib.amy
          sed 's/%//g' a.s > b.s
          sed 's/main/_main/g' b.s > c.s
          gcc c.s -o fib
          ./fib || [ $? -ne 55 ] && exit 1 || true

# todo: some testing
# releases?
