on:
  push:
    branches:
      - main

name: Windows

jobs:
  release:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Edit Cargo.toml
        run: |
          sed 's#codegem = { path = "../codegem" }#codegem = { git = "https://github.com/code-gem/codegem" }#' Cargo.toml > tmp
          rm Cargo.toml
          mv tmp Cargo.toml
          cat Cargo.toml

      - name: Release Build
        run: cargo build --release

# todo: some testing
# releases?
